data:
  data_file: data.json
  dataset_config: CC-MAIN-2014-10
  dataset_name: HuggingFaceFW/fineweb
  dataset_split: train
  num_training_samples: 100000
  tokenizer_training_samples: 10000
  validation_split: 0.1
files:
  best_model_path: best_model.pth
  checkpoint_path: checkpoint.pth
  log_dir: logs
  output_dir: outputs
model:
  dropout: 0.1
  embed_dim: 768
  ff_dim: 3072
  heads: 12
  max_block_size: 512
  num_layers: 12
  vocab_size: 50000
sampling:
  max_new_tokens: 512
  temperature_alt: 0.8
  temperature_default: 1.0
  top_k_default: 50
  top_p_default: 0.95
tokenizer:
  path: tokenizer.txt
  special_tokens:
    bos: <BOS>
    eos: <EOS>
    pad: <PAD>
    unk: <UNK>
training:
  batch_size: 32
  early_stopping_patience: 10
  epochs: 50
  eval_interval: 1000
  gradient_accumulation_steps: 1
  learning_rate: 0.0005
  max_grad_norm: 1.0
  mixed_precision: false
  save_interval: 5000
  scheduler_T_max: 1000
  scheduler_eta_min: 1.0e-06
  warmup_steps: 1000
  weight_decay: 0.01
